### ISSUE TITLE
Future annotations are incompatible with Python < 3.7

### ISSUE THREAD

**Issue by PeterJCLaw** [gorilla-co/s3pypi#101]
`s3pypi/index.py` uses future annotations, yet `pyproject.toml` claims support for Python >= 3.5.

https://github.com/gorilla-co/s3pypi/blob/8f22da9aff00e73e1f3498612925ddf403ce735b/s3pypi/index.py#L1

https://github.com/gorilla-co/s3pypi/blob/8f22da9aff00e73e1f3498612925ddf403ce735b/pyproject.toml#L15

What is the actual expected Python version requirement?

**Comment by mdwint** [comment]
Hi @PeterJCLaw. We're only testing with Python 3.7, 3.8, and 3.9: https://github.com/gorilla-co/s3pypi/blob/8f22da9aff00e73e1f3498612925ddf403ce735b/tox.ini#L2
The version constraint in `pyproject.toml` must have been forgotten, and needs to be updated to 3.7.
