### ISSUE TITLE
Does S3PyPI support extras?

### ISSUE THREAD

**Issue by beck3905** [gorilla-co/s3pypi#102]
I am still using v 0.11.0 of s3pypi.  Does it support extra dependencies?  My library has boto3 as an extra dependency so my expectation is that I can install `pip install my-package` from s3pypi and it will not include boto3.  And I should be able to install `pip install my-package[boto3]` and it will install boto3.  However, when I try the latter command I get "no matches found".

**Comment by mdwint** [comment]
I've never used extras with s3pypi, so I can't say for sure whether they are supported.
Could you show me how you defined the extra dependencies? Did you use [`extras_require` in setup.py](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)?
Does `pip install -vv my-package[boto3]` show any links that are found?

**Comment by beck3905** [comment]
I use poetry to define my extras.  The setup.py that poetry creates does use `extras_require`.  I did just figure out that it does work.  I just have to use quotes.  So `pip install my-package[boto3]` doesn't work, but `pip install 'my-package[boto3]'` does.
