### ISSUE TITLE
Migrating from 0.x -- no matching Route53Zone found

### ISSUE THREAD

**Issue by derek-adair** [gorilla-co/s3pypi#111]
1. My DNS is hosted @ google
2. I accidently deleted my old bucket
3. `terraform import module.s3pypi.aws_cloudfront_distribution.cdn {CDN_ID}` throws this error
4.  Starting fresh also throws this error

**Comment by mdwint** [comment]
This is expected. The Terraform configuration assumes that a Route 53 hosted zone exists for your domain, with a matching certificate in AWS Certificate Manager. If you don't have those, then you'll need to edit the Terraform configuration to match.
