### ISSUE TITLE
Detecting the name and version distribution on packages with hyphens

### ISSUE THREAD

**Issue by pssuils** [gorilla-co/s3pypi#118]
Currently on version 2.0 on packages that do have hyphen on the name, version and name are mistakenly detected. 

For example for a package which name is `something-cool`  when creating the distribution package (`python3 setup sdist`) generates the following file `something-cool-1.2.3.tar.gz`.  
Before it was detecting that the name of the package was `something-cool` and the version `1.2.3` now it identifies the name as `something`  and `cool` as the version of it. 

Are deliberate the changes to not take into account the names that have hyphens ? https://github.com/gorilla-co/s3pypi/blob/bb611d159f2681f0888f42019b6f6dae2ca28b93/s3pypi/core.py#L83-L91 

or could we go back to have something like 
`name, version = filename[: -len(ext)].rsplit("-", 1)` rather than `name, version = filename[: -len(ext)].split("-", 2)[:2]`

**Comment by mdwint** [comment]
This was changed deliberately. Previously we did it like this for all distributions except wheels, and now we added wheels.

According to [the spec](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format) the name part of the filename should not contain dashes.

How do you create distributions? If I create some using Poetry, the filenames are parsed fine.

**Comment by pssuils** [comment]
@mdwint we use nothing very fancy and rather vanilla. We use `setuptools==69.0.3` and `Python 3.10.12` 

We run `python3 setup.py sdist` with a very basic `setup.py` file, as an example:

```python
from setuptools import setup, find_packages

setup(
    name="something-cool",
    version="1.2.3",
    description="Super cool package",
    packages=find_packages("src"),
    package_dir={"something_cool": "src/something_cool"}
)
```

`src` folder contains the package folder called `something_cool`  after running `sdist` command the output filename is `something-cool-1.2.3.tar.gz` 

Maybe a silly mistake that I can't see?
