### ISSUE TITLE
region is not optional

### ISSUE THREAD

**Issue by ed9w2in6** [gorilla-co/s3pypi#119]
I got:
`boto3 client NoRegionError: You must specify a region error`
when trying to run `s3pypi upload ...`
Specifying the region via the `AWS_DEFAULT_REGION` seems to have resolved the issue.

May I ask if this is expected as the instruction seems to indicate that this is optional.

Related method:
`core.upload_packages()`

**Comment by mdwint** [comment]
The default region is usually set in your AWS credentials config file: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

You can override it using environment variables or the `--region` option.
