### ISSUE TITLE
Extra METADATA file in wheel causes wrong distribution name chosen

### ISSUE THREAD

**Issue by ethanhs-nv** [gorilla-co/s3pypi#129]
The current logic for selecting wheel distribution names breaks if there are multiple `METADATA` files in a distribution (e.g. you vendor a package and wish to keep the metadata).

Would you consider taking [`packaging` ](https://github.com/pypa/packaging) as a dependency to correctly extract the distribution names from wheels and sdists? The package [provides useful utilities](https://packaging.pypa.io/en/stable/utils.html) which correctly extract a distribution name from a wheel file name (and same for sdists).

Alternatively code to extract just the version and name from the wheel/sdist filename should be straightforward.

I'm happy to contribute a PR with either of these solutions.

**Comment by mdwint** [comment]
Sure, adding `packaging` sounds good.

What do the filenames look like that currently fail parsing? Do you have an example?

**Comment by ethanhs-nv** [comment]
I realized that this is actually correctly handled in s3pypi 2.0, I initially thought it affected all versions because I didn't see anything in the changelogs. Sorry for the noise!
