### ISSUE TITLE
Feature request: Support for pip search?

### ISSUE THREAD

**Issue by charleswhchan** [gorilla-co/s3pypi#36]
This is a cool project. `pip install` works as advertised, and I am curious if it's possible to support `pip search` as well? 

I don't know the technical details of the protocol used by pip, but thought I should ask anyway. 😃

**Comment by gbdlin** [comment]
`pip search` uses XML-RPC API, which

1. is deprecated by the PyPI
2. requires some active backend for the PyPI server

`s3pypi` is just deploying a static listing of the packages and files, there is no active element inside the s3 bucket that could serve that role. That being said, if you need the search feature, this is probably not the project you are looking for.

**Comment by mdwint** [comment]
I agree with @gbdlin's conclusion. `pip search` doesn't fit very well into this project, and I doubt it will ever be supported.
