### ISSUE TITLE
No sha256 hash of packages

### ISSUE THREAD

**Issue by andrei-shabanski** [gorilla-co/s3pypi#82]
Hi,

Right now, index.html doesn't contain sha256 hash of published packages. It causes the issue when we export requirements from pyproject.toml `poetry export --format="requirements.txt" > requirements.txt` and install them with `pip` (we use this approach to install packages inside docker image).

It would be great to calculate hashes and include them in index.html

**Comment by mdwint** [comment]
`poetry export` has a `--without-hashes` option. Does that help to work around the problem?

If anyone wants to contribute this feature, you can find the specification here:
https://www.python.org/dev/peps/pep-0503/

> The URL SHOULD include a hash in the form of a URL fragment with the following syntax: #\<hashname\>=\<hashvalue\>, where \<hashname\> is the lowercase name of the hash function (such as sha256) and \<hashvalue\> is the hex encoded digest.

**Comment by andrei-shabanski** [comment]
`--without-hashes` helps out us now. However, we'd prefer that pip checks hashes of all installing packages.

I've opened PR #83 that implements this feature. If you have an opportunity, please have a look at PR. Thanks!
