### ISSUE TITLE
Feature Request: Invalidate CloudFront Cache

### ISSUE THREAD

**Issue by ekevoo** [gorilla-co/s3pypi#84]
I would appreciate a parameter like `--cloud-front-distribution-id=AOEUAOEUAOEU` and, if provided, it will create a Cache Invalidation in CF in order to make sure all requests will obtain the most recent package index.

An additional option that is absolutely not required but it could be interesting would be waiting for the Cache Invalidation to be completed, or just outputing the invalidation ID in order to let a script wait for it.

**Comment by mdwint** [comment]
Index files are uploaded with `CacheControl="public, must-revalidate, proxy-revalidate, max-age=0"`, meaning they should not be cached. Have you experienced the index being out of date?

**Comment by ekevoo** [comment]
Oh I hadn't realized that. I manage several other CloudFront-based solutions and we explicitly invalidate the cache on updates, which is why I was confused when this didn't.

**Comment by mdwint** [comment]
Cache invalidations should be considered a last resort (and they cost money). You can use headers to control cache duration instead: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html

**Comment by ekevoo** [comment]
Our updates are infrequent enough that relying on caches (and invalidating them when appropriate, which is fully integrated on our build scripts) makes more sense than not caching. And the CloudFront+S3 costs are trivial compared to other costs such as EC2 & RDS. I would prefer to use caching in the PyPI service as well, but, again, associated costs are too trivial to matter.
