### ISSUE TITLE
Question: s3pypi on private bucket

### ISSUE THREAD

**Issue by m00lecule** [gorilla-co/s3pypi#85]
Hello Guys, I am just curious - is there a chance to deploy python pypi index on private s3?

**Comment by mdwint** [comment]
Hi @m00lecule. Certainly, private hosting is the point of this project. CloudFront can be secured using basic auth, and will access a private S3 bucket via an Origin Access Identity (OAI). For more details, check the README.md, CHANGELOG.md, Terraform configuration, or `s3pypi --help`.
