### ISSUE TITLE
dataclasses need backporting to be used on python 3.6

### ISSUE THREAD

**Issue by jaustinpage** [gorilla-co/s3pypi#87]
Hi,

While trying to use s3pypi, i ran into an issue where the dataclasses package was being imported, but, for python 3.6 we need to load in backported dataclasses module. I will have a pull request in that does this shortly. Thanks!

```
s3pypi --acl bucket-owner-full-control --s3-put-args ServerSideEncryption=AES256 --region us-west-2 --s3-endpoint-url https://bucket.vpce-an-endpointhashwashere.s3.us-east-2.vpce.amazonaws.com --bucket my-bucket-name dist/*
Traceback (most recent call last):
File "/home/user/myproject/.tox/publish/bin/s3pypi", line 5, in <module>
from s3pypi.__main__ import main
File "/home/user/myproject/.tox/publish/lib/python3.6/site-packages/s3pypi/__main__.py", line 9, in <module>
from s3pypi import __prog__, __version__, core
File "/home/user/myproject/.tox/publish/lib/python3.6/site-packages/s3pypi/core.py", line 5, in <module>
from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'````

**Comment by mdwint** [comment]
Hi @jaustinpage. We don't support Python 3.6 for this very reason. I'm unsure if now would be a good time to start supporting it, since Python 3.6 [is considered "end of life"](https://www.python.org/dev/peps/pep-0494/#lifespan) in a little over a month.

**Comment by jaustinpage** [comment]
agreed, I totally understand. Ill mark this one closed.
